name: Build, Migrate, and Deploy .NET 8 API to Azure Web App (Linux)

on:
  push:
    branches:
      - main
    paths:
      - 'src/Kanban.API/**'
      - 'Kanban.sln'
      - '.github/workflows/cd-backend.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: cd-backend-${{ github.ref }}
  cancel-in-progress: false

env:
  PROJECT_PATH: 'src/Kanban.API/Kanban.API.csproj'
  SOLUTION_PATH: 'Kanban.sln'
  PUBLISH_FOLDER: '${{ github.workspace }}/publish'
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'
  AZURE_WEBAPP_NAME: 'kanban-api'

jobs:
  build-test-migrate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build in Release mode
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run Tests
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install EF Core Tools
        run: dotnet tool install --global dotnet-ef --version 8.*

      - name: Run EF Core Migrations
        env:
          ASPNETCORE_ENVIRONMENT: Production
        run: |
          dotnet ef database update \
           --project ${{ env.PROJECT_PATH }} \
           --connection 'Server=tcp:kanban.database.windows.net,1433;Initial Catalog=free-sql-db-7052672;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Default;'

      - name: Publish project
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} -o ${{ env.PUBLISH_FOLDER }}

      - name: Deploy to Azure App Service (Linux)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_FOLDER }}